name: CI

on:
  pull_request:
    branches: 
      - main
      - tests

    paths-ignore:
      - "README.md"
      - "requirements_dev.txt"
  push:
    branches:
      - '**'


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7
      - name: Install dependencies for requirements and testing
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
      - name: Test with pytest
        run: |
          pytest --cov src tests/ --cov-fail-under=75
      - name: Lint with pylint
        run: |
          pylint src