name: CI

on:
  pull_request:
    branches: 
      - main
      - tests

    paths-ignore:
      - "README.md"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7
      - name: Install dependencies for requirements and testing
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install pytest-mock
          python -m pip install pytest-cov
      - name: Test with pytest
        run: |
          pytest --cov src tests/ --cov-fail-under=75